-- Migration: add global files list
-- Tabla global de archivos a respaldar

CREATE TABLE IF NOT EXISTS ar_global_files (
    id SERIAL PRIMARY KEY,
    file_name VARCHAR(255) NOT NULL UNIQUE,
    file_group VARCHAR(50) DEFAULT 'dbf',
    enabled BOOLEAN DEFAULT true,
    created_at TIMESTAMP DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_ar_global_files_name ON ar_global_files(file_name);

-- Insertar los 101 archivos
INSERT INTO ar_global_files (file_name) VALUES
('AJTFLU.DBF'), ('ASISTE.DBF'), ('CAJAS.DBF'), ('CANCFDI.DBF'), ('CANCFDI.FPT'),
('CANOTA.DBF'), ('CANOTA.DBT'), ('CANOTA.FPT'), ('CANOTAEX.DBF'), ('CARPORT.DBF'),
('CARPORT.FPT'), ('CASEMANA.DBF'), ('CAT_NEG.DBF'), ('CATPROD3.DBF'), ('CAT_PROD.DBF'),
('CCOTIZA.DBF'), ('CENTER.DBF'), ('CFDREL.DBF'), ('CG3_VAEN.DBF'), ('CG3_VAPA.DBF'),
('CLIENTE.DBF'), ('COBRANZA.DBF'), ('COMPRAS.DBF'), ('CONCXC.DBF'), ('CONVTODO.DBF'),
('CPEDIDO.DBF'), ('CPENDIE.DBF'), ('CPXCORTE.DBF'), ('CRMC_OBS.DBF'), ('CUENGAS.DBF'),
('CUNOTA.DBF'), ('DD_CONTROL.DBF'), ('DD_DATOS.DBF'), ('DESEMANA.DBF'), ('ES_COBRO.DBF'),
('EYSIENC.DBF'), ('EYSIPAR.DBF'), ('FACCFD.DBF'), ('FACCFD.FPT'), ('FLUJO01.DBF'),
('FLUJORES.DBF'), ('HISTORIA.DBF'), ('INVFSIC.DBF'), ('MASTER.DBF'), ('M_CONF.DBF'),
('MINTINV.DBF'), ('MOVCXCD.DBF'), ('MOVSINV.DBF'), ('N_CONF.DBF'), ('NEGADOS.DBF'),
('NOESTA.DBF'), ('NOHAY.DBF'), ('N_RESP.DBF'), ('N_RESP.DBT'), ('N_RESP_M.DBF'),
('N_RESP_M.DBT'), ('OBSDOCS.DBF'), ('PAGDOCS.DBF'), ('PAGMULT.DBF'), ('PAGSPEI.DBF'),
('PARAMS.DBF'), ('PARTCOMP.DBF'), ('PARTCOT.DBF'), ('PARXCAR.DBF'), ('PARVALES.DBF'),
('PAVACL.DBF'), ('PCOTIZA.DBF'), ('PEDIDO.DBF'), ('PEDIDO1.DBF'), ('PEDIDO2.DBF'),
('PPEDIDO.DBF'), ('PPENDIE.DBF'), ('RESP_PIN.DBF'), ('R_BBVA.DBF'), ('R_KUSHKI.DBF'),
('SERCFD2.DBF'), ('STOCK.DBF'), ('SUCURCTAI.DBF'), ('TABLA004.DBF'), ('TABLA005.DBF'),
('TERCAJAS.DBF'), ('TLSERVI.DBF'), ('USUARIOS.DBF'), ('VACLI.DBF'), ('VALES.DBF'),
('VALPEN.DBF'), ('VCPENDI.DBF'), ('VENDEDOR.DBF'), ('VENTA.DBF'), ('VENTA.DBT'),
('VENTA.FPT'), ('VENTAPP.DBF'), ('VPPENDI.DBF'), ('XCORTE.DBF')
ON CONFLICT (file_name) DO NOTHING;